# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fi.fhir.base
canonical: http://fhir.fi/finnish-base-profiles
name: FinnishBaseProfiles
title: Finnish Base Profiles
description: A core set of FHIR resources profiled for use in Finland, published and maintained by HL7 Finland
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2022+
releaseLabel: draft # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#FI "Finland" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 Finland
  url: https://www.hl7.fi/
  # email: mikael@sensotrend.com

dependencies:
  hl7.fhir.uv.ipa: 0.1.0

pages:
  index.md:
    title: Home
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  downloads.md:
    title: Downloads
  history.md:
    title: Version History

parameters: 
  ipa-comparison: "{last}" # "{current}" | "{last}"

menu:
  Home: index.html
#  Table of Contents: toc.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
#  Examples: examples.html
#  Artifacts: artifacts.html
  Downloads: downloads.html
