# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.fi.base
canonical: https://hl7.fi/fhir/finnish-base-profiles
name: FinnishBaseProfiles
title: Finnish Base Profiles
description: A core set of FHIR resources profiled for use in Finland, published and maintained by HL7 Finland
status: draft # draft | active | retired | unknown
version: 1.0.0-rc22
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2022+
releaseLabel: qa-preview # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#FI "Finland" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 Finland
  url: https://www.hl7.fi/
  email: mikael@sensotrend.com

dependencies:
  hl7.fhir.uv.ipa: 1.0.0

resources:
  Bundle/diabetes-data-bundle:
    name: Patient generated glucose observations and insulin administrations as a bundle, in Finnish
    description: A Bundle of resources uploaded by a patient from a insulin delivery system containing both a continuous glucose sensor and an insulin pump.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Bundle/diabetes-data-bundle-kantaphr-r4-en:
    name: Patient generated glucose observations and insulin administrations as a bundle, in English
    description: A Bundle of resources uploaded by a patient from a insulin delivery system containing both a continuous glucose sensor and an insulin pump. Conforms to Kanta PHR R4 profiles.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Bundle/diabetes-data-bundle-kantaphr-sv:
    name: Patient generated glucose observations and insulin administrations as a bundle, in Swedish
    description: A Bundle of resources uploaded by a patient from a insulin delivery system containing both a continuous glucose sensor and an insulin pump. Conforms to Kanta PHR STU3 profiles.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Medication/medicationesim1:
    name: Myyntiluvallinen lääkevalmiste
    description: An example Medication instance from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient-medication
  Medication/medicationesim2:
    name: Myyntiluvallinen lääkevalmiste, joka on PKV-lääke
    description: An example Medication instance from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-medication
  MedicationAdministration/a4d97476-39fa-46c6-bf2e-1fb153a7bbe3:
    name: Kanta PHR - Insulin dosage optional
    description: An example insulin dosage with optional elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-medication-administration
  MedicationAdministration/a4d97476-39fa-46c6-bf2e-1fb153a7bbe2:
    name: Kanta PHR - Insulin dosage mandatory
    description: An example insulin dosage with mandatory elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-medication-administration
  MedicationAdministration/medication-administration-insulin-basal-dose-kanta-stu3-sv:
    name: MedicationAdministration example of insulin basal dose
    description: A basal dose of fast-acting insulin, administred with an insulin pump. Conforms to the Kanta PHR profile, version STU3. In Swedish.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-medication-administration
  MedicationAdministration/medication-administration-insulin-dose-temp-basal-rate-kanta-en:
    name: MedicationAdministration example of temporary basal rate
    description: A temporarily adjusted basal dose of fast-acting insulin, administred with an insulin pump. Conforms to the Kanta PHR profile. In English.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-medication-administration
  MedicationAdministration/medication-administration-insulin-bolus-dose-fi:
    name: MedicationAdministration example of insulin dose
    description: A bolus dose of fast-acting insulin, administred with an insulin pump. In Finnish.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-medication-administration
  MedicationRequest/medicationrequestesim1:
    name: "1 tabletti 2 kertaa päivässä"
    description: An example MedicationRequest from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient-medication-request
  MedicationRequest/medicationrequestesim2:
    name: "2 tablettia aamulla ja 1 tabletti illalla 6 päivän ajan"
    description: An example MedicationRequest from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient-medication-request
  MedicationRequest/medicationrequestesim3:
    name: "1-2 tablettia kerran päivässä"
    description: An example MedicationRequest from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient-medication-request
  MedicationRequest/medicationrequestesim4:
    name: "1-2 tablettia 1-3 kertaa päivässä"
    description: An example MedicationRequest from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient-medication-request
  MedicationRequest/medicationrequestesim5:
    name: "Maanantaisin 1 tabletti ja tarvittaessa keskiviikkoisin 0,5 tablettia 01.06.2020 - 31.12.2020"
    description: An example MedicationRequest from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient-medication-request
  MedicationRequest/medicationrequestesim6:
    name: "Lääke tauolla 1.3.2020 - 30.6.2020. Taukoa edeltävä annostus: 25 mg klo 08:00 10 päivän ajan ihon alle"
    description: An example MedicationRequest from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient-medication-request
  MedicationRequest/medicationrequestesim7A:
    name: "1 tabletti 2 kertaa päivässä 5 päivän ajan 15.1.2021 alkaen"
    description: An example MedicationRequest from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient-medication-request
  MedicationRequest/medicationrequestesim7B:
    name: "1 tabletti 2 kertaa päivässä 5-7 päivän ajan 15.1.2021 alkaen"
    description: An example MedicationRequest from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient-medication-request
  MedicationRequest/medicationrequestesim8:
    name: "Tarvittaessa 2 tablettia 3 kertaa viikossa 16.2.2021 alkaen"
    description: An example MedicationRequest from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient-medication-request
  MedicationRequest/medicationrequestesim9:
    name: "Tarvittaessa 1-2 tippaa 3-4 tunnin välein"
    description: An example MedicationRequest from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-medication-request
  Observation/bloodglucose-as-text:
    name: Kanta PHR - blood glucose result as text
    description: This is an example, where measurement device has failed to measure numerical value for the blood glucose but the device still can store some result in the narrative element. In this case code 'astext' must be used in dataAbsentReason.coding.code.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/bloodglucose-data-absent:
    name: Kanta PHR - blood glucose with data absent
    description: This is an example, where measurement device has failed to measure blood glucose reading. In this case 'error' must be used in dataAbsentReason.coding.code.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/bloodglucose-max:
    name: Kanta PHR - blood glucose optional
    description: An example blood glucose measurement with optional elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/bloodglucose-min:
    name: Kanta PHR - blood glucose mandatory
    description: An example blood glucose measurement with mandatory elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/bloodpressure-max:
    name: Kanta PHR - blood pressure optional
    description: An example blood pressure measurement with optional elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/bloodpressure-min:
    name: Kanta PHR - blood pressure mandatory
    description: An example blood pressure measurement with mandatory elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/bodyweight-max:
    name: Kanta PHR - body weight optional
    description: An example body weight measurement with optional elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/bodyweight-min:
    name: Kanta PHR - body weight mandatory
    description: An example body weight measurement with mandatory elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/542ae72e-c3b0-404f-8c06-8f77441e89f8:
    name: Kanta PHR - calorie intake optional
    description: An example calorie intake measurement with optional elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/542ae72e-c3b0-404f-8c06-8f77441e89f7:
    name: Kanta PHR - calorie intake mandatory
    description: An example calorie intake measurement with mandatory elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/2894b2e6-7ebf-4c33-93e4-31935effff22:
    name: Kanta PHR - carbohydrate intake optional
    description: An example estimated carbohydrate intake measurement with optional elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/2894b2e6-7ebf-4c33-93e4-31935effff21:
    name: Kanta PHR - carbohydrate intake mandatory
    description: An example estimated carbohydrate intake measurement with mandatory elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/71831b54-1a80-47c5-ba84-0180a5eb784b:
    name: Kanta PHR - exercise tracking optional
    description: An example exercise tracking measurement with optional elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/71831b54-1a80-47c5-ba84-0180a5eb784a:
    name: Kanta PHR - exercise tracking mandatory
    description: An example exercise tracking measurement with mandatory elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/48983b8b-ead3-4206-9583-fcdd40d762b7:
    name: Kanta PHR - MET measurement optional
    description: An example MET measurement with optional elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/48983b8b-ead3-4206-9583-fcdd40d762b6:
    name: Kanta PHR - MET measurement mandatory
    description: An example MET measurement with mandatory elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/mtvpa-max:
    name: Kanta PHR - physical activity optional
    description: An example physical activity measurement with optional elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/mtvpa-min:
    name: Kanta PHR - physical activity mandatory
    description: An example physical activity measurement with mandatory elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/1153859e-0c86-1000-abb8-511d0000b222:
    name: Kanta PHR - body height optional
    description: An example body height measurement with optional elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/4137d1c4-1e87-4e86-8c15-344ad086e3f9:
    name: Kanta PHR - step count optional
    description: An example step count measurement with optional elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Observation/4137d1c4-1e87-4e86-8c15-344ad086e3f8:
    name: Kanta PHR - step count mandatory
    description: An example step count measurement with mandatory elements.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-observation
  Organization/1.2.246.10.31045308.10002.0:
    name: A high level organization
    description: Organization on Wellbeing Services County level
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-organization
  Organization/organizationesim1:
    name: Testi terveysasema
    description: An example Organization from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-organization
  Organization/organizationesim2:
    name: Simple Organization example
    description: An example Organization from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-organization
  Patient/36749a02-1710-44e7-aa76-0e934eb7860a:
    name: Kanta PHR - patient 3
    description: An example patient for Kanta PHR.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient
  Patient/patientesim1:
    name: Karen van der Hentenryck
    description: An example patient from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-patient
  Practitioner/practitioneresim1:
    name: Lars van der Knaapi
    description: An example practitioner from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-practitioner
  PractitionerRole/practitionerRoleesim1:
    name: A simple practitioner role
    description: An example PractitionerRole instance from Kanta Prescription API
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/fi-base-practitioner-role
  Patient/25a53703-27f9-4354-8f1b-a8b2f8f3ee86:
    name: A dummy patient entry
    description: A patient id supporting other examples, not included in the guide.
    exampleBoolean: false
  Patient/36749a02-1710-44e7-aa76-0e934eb4321a:
    name: A dummy patient entry
    description: A patient id supporting other examples, not included in the guide.
    exampleBoolean: false
  Patient/77c2c8d2-11ce-41d5-8150-75489f8b0b0a:
    name: A dummy patient entry
    description: A patient id supporting other examples, not included in the guide.
    exampleBoolean: false
  Patient/bb13623e-2673-4b3e-85d6-5c42f5333cde:
    name: A dummy patient entry
    description: A patient id supporting other examples, not included in the guide.
    exampleBoolean: false
  Patient/cafbe8e7-38fe-4807-b995-6770e5390365:
    name: A dummy patient entry
    description: A patient id supporting other examples, not included in the guide.
    exampleBoolean: false
  Patient/daf8ca40-b46c-4c6b-99d5-d3a1b77074ad:
    name: A dummy patient entry
    description: A patient id supporting other examples, not included in the guide.
    exampleBoolean: false
  Patient/f1fa0b52-eccf-44af-96c7-84a3251bb22c:
    name: A dummy patient entry
    description: A patient id supporting other examples, not included in the guide.
    exampleBoolean: false
  Patient/7257379:
    name: A dummy patient entry
    description: A patient id supporting other examples, not included in the guide.
    exampleBoolean: false
  Provenance/custodian-public-healthcare-kela:
    name: Provenance example for Kanta
    description: This example resource shows how information custodianship can be implemented with the support of the Finnish base profiles. It is derived from a provided example.
    exampleCanonical: https://hl7.fi/fhir/finnish-base-profiles/StructureDefinition/kanta-document-metadata-profile

pages:
  index.md:
    title: Home
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology
  examples.md:
    title: Examples
  downloads.md:
    title: Downloads
  versions.md:
    title: Version History

parameters: 
  ipa-comparison: "{last}" # "{current}" | "{last}"
  extension-domain: [ http://hl7.fi/, http://phr.kanta.fi/, http://resepti.kanta.fi/ ]

menu:
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Examples: examples.html
  Downloads: downloads.html
